version: '3.8'

services:
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    environment:
      - DATABASE_URL=postgresql://cj_sit722_juu5_user:l5MuIlfcMoaejW4Et0cwoJG9rGqP7qlL@dpg-crmlebdumphs739gk8v0-a.oregon-postgres.render.com/cj_sit722_juu5
    depends_on:
      - postgres

  inventory_management:
    build:
      context: ./inventory_management  
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  
    environment:
      - DATABASE_URL=postgresql://cj_sit722_juu5_user:l5MuIlfcMoaejW4Et0cwoJG9rGqP7qlL@dpg-crmlebdumphs739gk8v0-a.oregon-postgres.render.com/cj_sit722_juu5
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: library_db  
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: admin  
    ports:
      - "5432:5432"  
