apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: cjpcontainer.azurecr.io/project_part3-book_catalog:latest 
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgresql://cj_sit722_cg57_user:bTMfuBFEGqO4noI36IaKxacXRa6J25lB@dpg-crrl9h56l47c73cktv3g-a.oregon-postgres.render.com/cj_sit722_cg57"  # Update as necessary

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: cjpcontainer.azurecr.io/project_part3-inventory_management:latest 
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              value: "postgresql://cj_sit722_cg57_user:bTMfuBFEGqO4noI36IaKxacXRa6J25lB@dpg-crrl9h56l47c73cktv3g-a.oregon-postgres.render.com/cj_sit722_cg57"  # Update as necessary

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: book-catalog

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  type: LoadBalancer
  ports:
    - port: 8081
  selector:
    app: inventory-management
